import 'package:firestore_access_policy/firestore_access_policy.dart';
import 'package:test/test.dart';

void main() {
  group('FirestoreRulesGenerator', () {
    test('emits helpers, match blocks, and deny fallback', () {
      const isAuthenticatedHelper = HelperFunction(
        name: 'isAuthenticated',
        body: 'return request.auth != null;',
      );

      final listPolicy = AccessPolicy(
        path: ResourcePath.parse('lists/{listId}'),
        description: 'Collaborative lists',
        rules: {
          PolicyAction.read: [
            PolicyRule(
              And([
                Authenticated(),
                InMapKeys('members'),
              ]),
            ),
          ],
          PolicyAction.delete: [
            PolicyRule(AuthUidEqualsField('createdBy')),
          ],
        },
      );

      final output = const FirestoreRulesGenerator().generate(
        FirestoreRulesFile(
          headerComment: 'Generated by firestore_access_policy',
          helpers: [isAuthenticatedHelper],
          policies: [listPolicy],
        ),
      );

      expect(output, contains("rules_version = '2';"));
      expect(output, contains('service cloud.firestore'));
      expect(output, contains('function isAuthenticated()'));
      expect(output, contains('match /lists/{listId}'));
      expect(output, contains('allow read: if'));
      expect(output, contains('request.auth != null'));
      expect(output, contains('request.auth.uid in resource.data.members.keys()'));
      expect(
        output,
        contains('allow delete: if request.auth.uid == resource.data.createdBy'),
      );
      expect(output, contains('match /{document=**}'));
      expect(output, contains('allow read, write: if false'));
    });
  });

  group('StorageRulesGenerator', () {
    test('emits storage.rules structure', () {
      final profilePhotos = StorageAccessPolicy(
        path: StorageResourcePath.parse('users/{userId}/profile.jpg'),
        rules: {
          StoragePolicyAction.read: [
            StoragePolicyRule(const Authenticated()),
          ],
          StoragePolicyAction.write: [
            StoragePolicyRule(
              PathParamEquals('userId', 'request.auth.uid'),
            ),
          ],
        },
      );

      final output = const StorageRulesGenerator().generate(
        StorageRulesFile(policies: [profilePhotos]),
      );

      expect(output, contains("rules_version = '2';"));
      expect(output, contains('service firebase.storage'));
      expect(output, contains('match /b/{bucket}/o'));
      expect(output, contains('match /users/{userId}/profile.jpg'));
      expect(output, contains('allow read: if request.auth != null'));
    });
  });
}
