/// Default strings for generated rules files.
abstract final class RulesFileDefaults {
  /// Neutral header for [FirestoreRulesFile.headerComment].
  static const firestoreHeaderComment =
      'Generated by firestore_access_policy — review before deploy';

  /// Neutral header for [StorageRulesFile.headerComment].
  static const storageHeaderComment =
      'Generated by firestore_access_policy — review before deploy';
}
