import '../access_policy.dart';
import '../policy_action.dart';

/// A single rules test case (for documentation / future emulator harness).
final class RulesTestCase {
  /// Describes one scenario for a generated rules test skeleton.
  const RulesTestCase({
    required this.description,
    required this.path,
    required this.action,
    required this.expectAllowed,
    this.authUid = 'testUser',
  });

  /// Human-readable test name.
  final String description;

  /// Document path under test (e.g. `lists/abc`).
  final String path;

  /// CRUD action being exercised.
  final PolicyAction action;

  /// Whether the operation should be allowed.
  final bool expectAllowed;

  /// Authenticated user id for the scenario.
  final String authUid;
}

/// Generates a Dart test file skeleton for manual or emulator-based verification.
final class RulesTestGenerator {
  /// Creates a rules test skeleton generator.
  const RulesTestGenerator();

  /// Returns Dart test source with TODO stubs for emulator wiring.
  String generate({
    required String packageName,
    required List<AccessPolicy> policies,
    List<RulesTestCase> cases = const [],
    String testFileName = 'generated_rules_test.dart',
  }) {
    final buffer = StringBuffer()
      ..writeln('// GENERATED by firestore_access_policy — do not edit by hand.')
      ..writeln('// File: $testFileName')
      ..writeln('//')
      ..writeln('// Wire to the Firebase Rules Unit Testing library when ready:')
      ..writeln('// https://firebase.google.com/docs/rules/unit-tests')
      ..writeln()
      ..writeln("import 'package:test/test.dart';")
      ..writeln()
      ..writeln('void main() {')
      ..writeln("  group('Generated policy coverage', () {");

    for (final policy in policies) {
      buffer.writeln(
        "    test('documents ${policy.path.matchPath}', () {",
      );
      buffer.writeln('      // TODO: emulator tests for:');
      for (final action in PolicyAction.values) {
        final rules = policy.rules[action];
        if (rules == null || rules.isEmpty) continue;
        buffer.writeln('      //   allow ${_actionName(action)}');
      }
      buffer.writeln('    });');
    }

    for (final testCase in cases) {
      final safeName = testCase.description.replaceAll("'", r"\'");
      buffer.writeln("    test('$safeName', () {");
      buffer.writeln('      // path: ${testCase.path}');
      buffer.writeln('      // action: ${_actionName(testCase.action)}');
      buffer.writeln('      // auth: ${testCase.authUid}');
      buffer.writeln('      // expect allowed: ${testCase.expectAllowed}');
      buffer.writeln('    }, skip: \'Add firebase_rules_unit_testing harness\');');
    }

    buffer
      ..writeln('  });')
      ..writeln('}');

    return buffer.toString();
  }

  String _actionName(PolicyAction action) => switch (action) {
        PolicyAction.read => 'read',
        PolicyAction.create => 'create',
        PolicyAction.update => 'update',
        PolicyAction.delete => 'delete',
      };
}
